# configure appearance
# $HOME/.monicarc   #monitor calibration
[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources

# input method settings
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
ibus-daemon -drx

picom -b --config $HOME/.config/picom/picom.conf

# disable trackpoint center button and touchpad
if [ $(lsmod | grep thinkpad | wc -l ) -gt 0 ]; then
  xinput --disable $(xinput list --id-only "$(xinput list --name-only | grep -i Synaptics)")
fi

# typematic delay and rate
xset r rate 150 40

# load system configuration
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# adjust monitors
$HOME/.dotfiles/bin/auto-monitor-adjuster

# start desktop
exec i3
