#!/bin/bash

set -eu

mitamae_version="1.11.7"

case "$(uname)" in
  "Linux")
    mitamae_bin="mitamae-x86_64-linux"
    mitamae_sha256="4e846c132b15749d0a826f01c52618fa7c04ed1514e074cd0d108e5810188458"
    ;;
  "Darwin")
    mitamae_bin="mitamae-x86_64-darwin"
    mitamae_sha256="60e689bc81daca1a5a1b982c345f839bbf7d4b240f69d98b2563e7affa837491"
    ;;
  *)
    echo "Error: unexpected uname"
    exit 1
    ;;
esac

mitamae_origin="https://github.com/itamae-kitchen/mitamae/releases/download/v${mitamae_version}/${mitamae_bin}.tar.gz"

dot_dir="$(cd "$(dirname "$0")"; cd ..; pwd)"
tar="${dot_dir}/bin/mitamae-${mitamae_bin}.tar.gz"
bin="/usr/local/bin/mitamae"

if [ ! -e "${bin}" ]; then
  curl -o "${tar}" -fL "${mitamae_origin}"
  downloaded_sha256="$(openssl dgst -sha256 "${tar}" | cut -d ' ' -f 2)"
  if [ "${mitamae_sha256}" != "${downloaded_sha256}" ]; then
    echo "Error: invalid checksum"
    echo "expected: ${mitamae_sha256}"
    echo "actual  : ${downloaded_sha256}"
    exit 1
  fi
  tar xvzf "${tar}"
  sudo mv "${mitamae_bin}" "${bin}"
  rm "${tar}"
fi
