#!/bin/bash

set -eu

[ ! -e "$HOME/.ssh/id_ed25519.pub" ] && ssh-keygen -t ed25519

GITHUB_PUBKEY=$(cat "$HOME/.ssh/id_ed25519.pub")

read -rs -p 'GitHub Personal Access Token: ' GITHUB_PAT
echo

curl -XPOST \
  -H "Content-Type: application/json" \
  -H "Authorization: token $GITHUB_PAT" \
  -d "{\"title\": \"$USER@$HOSTNAME\", \"key\": \"$GITHUB_PUBKEY\"}" \
  "https://api.github.com/user/keys"
