#!/bin/bash

set -eu

[ ! -e $HOME/.ssh/id_rsa.pub ] && ssh-keygen

GITHUB_PUBKEY=`cat $HOME/.ssh/id_rsa.pub`

read    -p 'GitHub Username: ' GITHUB_USERNAME
read -s -p 'GitHub Password: ' GITHUB_PASSWORD
echo
read -s -p 'GitHub OTP: '      GITHUB_OTP
echo

curl -XPOST \
  -H "Content-Type: application/json" \
  -H "X-GitHub-OTP: $GITHUB_OTP" \
  --basic -u "$GITHUB_USERNAME:$GITHUB_PASSWORD" \
  -d "{\"title\": \"$USER@$HOSTNAME\", \"key\": \"$GITHUB_PUBKEY\"}" \
  "https://api.github.com/user/keys"
